name: Deploy WASM Site to GitHub Pages (/docs)

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed to update the docs folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Enable Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build WASM site
        run: ./gradlew wasmJsBrowserDistribution

      - name: Clear docs folder
        run: |
              rm -rf docs/*
              mkdir -p docs

      - name: Copy output to docs
        run: cp -r composeApp/build/dist/wasmJs/productionExecutable/* docs/

      - name: Deploy to live
        run: |
          git config --global user.name "osawant023"
          git config --global user.email "osawant023@gmail.com"
          git add docs
          git commit -m "Deploy latest wasm build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
